apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vc8zum117-python
  janus-idp.io/tekton: vc8zum117-python
  backstage.io/kubernetes-id: vc8zum117-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vc8zum117-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
