apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vc8zum117-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vc8zum117-python 
  name: vc8zum117-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vc8zum117-python 
